Update zh_cn.lang
TechReborn/TechReborn pull request #1391
Opened 2017-12-29 05:26 UTC by DYColdWind

2017-12-29 12:27 UTC, modmuss50 requested changes
Almost correct, but this wont work as it only replaces `$fluid$` with the fluid name.

2017-12-29 12:27 UTC, modmuss50 commented on src/main/resources/assets/techreborn/lang/zh_cn.lang
> +item.techreborn.cell.fluid.name=$流体$单元
This wont work, you will want to have the following:

`item.techreborn.cell.fluid.name=$fluid$单元`

2017-12-29 23:29 UTC, DYColdWind commented on src/main/resources/assets/techreborn/lang/zh_cn.lang
> +item.techreborn.cell.fluid.name=$流体$单元
Thank you for pointing out the mistake ...

2017-12-29 23:51 UTC, liach commented on src/main/resources/assets/techreborn/lang/zh_cn.lang
> +item.techreborn.cell.fluid.name=$流体$单元
Looks funky! modmuss, you should use upper case characters to better indicate such tokens.

2017-12-30 01:58 UTC, modmuss50 approved these changes

2017-12-30 01:58 UTC, merged