Update ru_ru.lang
TechReborn/TechReborn pull request #1582
Opened 2018-08-18 14:54 UTC by EnGinners

2018-08-18 14:56 UTC, modmuss50 commented
There is another large russian PR for languages, I have no idea which one is more accurate.

Calling @drcrazy to take a look at this and #1580 and figure out which one is best.

2018-08-19 16:45 UTC, drcrazy requested changes
Almost same as https://github.com/TechReborn/TechReborn/pull/1580/files except couple of items. Guys, can you join you efforts, please?

2018-08-28 10:39 UTC, drcrazy approved these changes

2018-08-28 10:40 UTC, merged

2018-08-30 22:04 UTC, modmuss50 commented
For your information, translation is now handled over at : [https://translate.techreborn.ovh/](https://translate.techreborn.ovh/). This should make it easier and quicker for you to contribute translations.