add c:workbench to autocrafter
TechReborn/TechReborn pull request #2840
Opened 2022-03-01 12:36 UTC by xanthian

to include compat for byg, betterx and other mods with added crafting tables
tested working in dev, vanilla crafting table unaffected by change

2022-03-01 18:38 UTC, Ayutac requested changes
I would recommend only leaving the c:workbench in the recipe and add the tag to our common tags. Is cleaner.

2022-03-23 14:12 UTC, xanthian commented
what changes are required here? 
no reason not to leave both there, alleviates any potential issues with tags

2022-03-23 18:22 UTC, xanthian commented
added new c tag for workbench to include vanilla table, removed entry from recipe to make it 'cleaner'

2022-03-25 11:32 UTC, Ayutac approved these changes

2022-03-25 11:33 UTC, merged