Cache BFS Result and use when its possible
TechReborn/TechReborn pull request #2843
Opened 2022-03-02 16:14 UTC by aria1th

Reduces 8.5mspt -> 5.5mspt for 9300 glass fiber cables.
![2022-03-03_01 04 31](https://user-images.githubusercontent.com/35677394/156401681-c2066025-da95-4292-b723-e6b9946d269b.png)
![2022-03-03_00 59 40](https://user-images.githubusercontent.com/35677394/156401695-2a2d6667-7acf-4449-a3d1-03ad94f50f34.png)
Confirmed working in sp / mp but test / review required, there might be edge case I'm not aware of.

2022-03-02 16:33 UTC, aria1th commented
I guess it might require blockEntity.isRemoved() check for keys and remove it too.

2022-03-02 18:08 UTC, Technici4n requested changes
It looks like this is going to leak a large amount of memory...

I am really not convinced by this optimization, halving the tick time is not that impressive for something that should be a large complexity improvement?

I would suggest profiling the algorithm to check if something can be made faster inside of the BFS (getBlockEntity can be made much faster with BlockApiCache).

2022-03-02 20:23 UTC, aria1th commented
Profiles with spark : before opt
https://spark.lucko.me/CgPVQDSCAh
After opt
https://spark.lucko.me/5SRQtHpzf6
and yes I agree if getBlockEntity can be speed up, it will be much faster... 

And I checked if *just* BlockApiCache can help it, seems its answer is no, well its almost costing 42mspt ... or I misimplemented it? actually without any patch it costs 53mspt yes....
https://spark.lucko.me/LgfBD6ARgI
https://spark.lucko.me/LDciduPLNM

but I'll add ApiCache because its very fast

2022-03-02 20:30 UTC, aria1th commented
and yeah its vanilla bug makes it 40mspt...

2022-03-02 22:29 UTC, Technici4n commented
Well you're not using BlockApi**Cache** as far as I can tell?

2022-03-02 22:30 UTC, Technici4n commented
It should be fine to just re-use whatever cache is used for the energy API already.

2022-03-03 06:10 UTC, aria1th commented
it wasn't blockentity cache (or I was misleading something?) so I implemented with hashmap cache and works pretty well,
https://spark.lucko.me/uHt2AWSE5h

So there's totally no getBlockEntity lag now, but most of the lag is coming from simulation of transfer amount and sorting, when cable has lower energy than required. Do we really need to prioritize cable transfer? I mean, real electricity never works that way. By removing sort / shuffle and just implementing simple iteration, it can totally remove cable lag

2022-03-03 06:27 UTC, aria1th commented
https://spark.lucko.me/bMvVvxqo0I
It was missing cache for blockentity Itself, added it and now its 10mspt with 9300 cables

2022-03-03 14:02 UTC, Technici4n commented
> Profiles with spark : before opt
https://spark.lucko.me/CgPVQDSCAh
After opt
https://spark.lucko.me/5SRQtHpzf6
and yes I agree if getBlockEntity can be speed up, it will be much faster...

First profile, relevant part:
![image](https://user-images.githubusercontent.com/13494793/156578092-28184931-1ae5-4df4-ae34-25b0cb502239.png)

Second profile, relevant part:
![image](https://user-images.githubusercontent.com/13494793/156578278-bacac55b-9083-488e-9277-c4b65a75754c.png)

It seems that there is actually no optimization?

2022-03-03 14:03 UTC, Technici4n commented
> Do we really need to prioritize cable transfer? I mean, real electricity never works that way. By removing sort / shuffle and just implementing simple iteration, it can totally remove cable lag

Yes, cables properly splitting energy is a feature that should be kept.

2022-03-03 14:25 UTC, aria1th commented
its 6:4 to 7:3 optimization so minor, and that didn't contain proper caching.. now it does it properly. BFS caching only reduces lag by 33%, but yes as you said, Block Entity was major problem and caching it solved everything. Thank you for BlockApiCache, its very promising. I'll update final report in this comment.

2022-03-03 14:39 UTC, Technici4n commented
#2844 is how I expected it to be done.

I also don't see how your PR optimizes the BFS since the cache is cleared every tick.

2022-03-03 14:44 UTC, aria1th commented
No, its not cleared every tick - it only calls tickCache if gatherCable (BFS search) is required. Look at https://spark.lucko.me/bMvVvxqo0I
gatherCable method is never called when BlockEntity is not dirty.

2022-03-03 14:54 UTC, Technici4n commented
Ah, my bad. I am still very confused by the `HashSet<HashSet<>>` and I find your code quite hard to understand. I also have concerns about memory being properly cleared when the whole cable set is removed in one tick. And finally you don't seem to properly check if cables are in a ticking chunk or not, which you should to avoid chunk loading loops.

Overall I think this PR is unnecessary given #2844.

2022-03-03 14:54 UTC, closed without merging

2022-03-03 15:02 UTC, aria1th commented
Well I tested extreme cases by filling 25x25x25 cables by command block and confirmed it didn't leak any memory too, 

> https://spark.lucko.me/bMvVvxqo0I It was missing cache for blockentity Itself, added it and now its 10mspt with 9300 cables
> 
> There's no memory leak : Memory report : https://spark.lucko.me/fZ3q9PMuXQ https://spark.lucko.me/9AhGfD8Hd1 (40min with intensive fill repeat for 10k cables)

It consumed 56MB constantly, and memory didn't leak, I ran test for 5 hours and no mspt / ram usage increase was found.
But I agree its hard to read and yeah chunkloading check was missing... I hope your pr being merged quickly, since cables are really laggy in current impl.