Reworking UU matter
TechReborn/TechReborn pull request #2961
Opened 2022-05-24 19:10 UTC by Ayutac

Tell me what you think of it so far :)

1.19 version of #2959

2022-05-27 05:01 UTC, Ayutac commented
I'm satisfied so far. Some uu recipes got changed, but this was inevitable. The idea is that adding non-uu to the recipes makes for much more available recipes in the less-uu-requiring category. Lore-wise uu matter works well if it can connect to some existing matter.

Since I made a sea lanterns recipe I got rid of the grind shards->crystals recipe I loathed for some time. The reason is that I want to keep glowstone and sea crystals as two different sources of light and since shards don't emit light, the recipe made no sense on the lore I built up.

2022-06-01 04:25 UTC, drcrazy requested changes
Please, fix names and namespaces

2022-06-01 04:25 UTC, drcrazy commented on src/main/resources/data/techreborn/recipes/crafting_table/uu_matter/wood/arcadia_wood.json
> +    "item": "minecraft:arcadia_wood"
Is it acacia?

2022-06-01 04:26 UTC, drcrazy commented on src/main/resources/data/techreborn/recipes/crafting_table/uu_matter/ore/coal_ore.json
> +      "item": "techreborn:stone"
minecraft namespace

2022-06-01 04:26 UTC, drcrazy commented on src/main/resources/data/techreborn/recipes/crafting_table/uu_matter/sapling/birch_sapling.json
> +      "item": "techreborn:plant_ball"
plantball, without underscore

2022-06-01 10:36 UTC, Ayutac commented
Really weird, did not show these errors earlier. Will correct once i get home today :)

2022-06-11 20:46 UTC, merged